title: Yan Li
author: Yan Li
email: liyan.career@gmail.com
description: >-
  Welcome! This is Yan Li's projects page. 

baseurl: "" # change if your repo has different name
url: https://yanxxx.github.io/Projects/
githubusername: Yanxxx

# Build settings
theme: minima
plugins: 
      - jekyll-feed

# File structure settings
image_path: /images

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



collections:
  projects:
    output: true
    permalink: /projects/:name

sass:
  sass_dir: _sass
  style: compressed


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页
